/**
 * Loads /certificates/_manifest.json (generated by scripts/sync-projects-index.js).
 */
function publicBase () {
  return process.env.BASE_URL || '/'
}

export async function loadCertificatesManifest () {
  const base = publicBase().replace(/\/?$/, '/')
  const url = `${base}certificates/_manifest.json`
  const res = await fetch(url)
  if (!res.ok) {
    return { certificates: [] }
  }
  try {
    const data = await res.json()
    const list = Array.isArray(data.certificates) ? data.certificates : []
    return { certificates: list }
  } catch {
    return { certificates: [] }
  }
}

/**
 * Builds a URL to a PDF under public/certificates/ (relative path uses / separators).
 */
export function certificatePdfUrl (relativePath) {
  const base = publicBase().replace(/\/?$/, '/')
  const encoded = String(relativePath)
    .split('/')
    .filter(Boolean)
    .map((seg) => encodeURIComponent(seg))
    .join('/')
  return `${base}certificates/${encoded}`
}
