/**
 * Loads project and highlight manifests from /public/projects/ and /public/highlights/
 * (served as static assets).
 * Image filenames come from each folder's _images.json (generated by scripts/sync-projects-index.js)
 * unless project.json sets media.images explicitly.
 */
function publicBase () {
  return process.env.BASE_URL || '/'
}

export async function loadProjectSlugs (folder = 'projects') {
  const base = publicBase()
  const indexUrl = `${base}${folder}/_index.json`
  const res = await fetch(indexUrl)
  if (!res.ok) {
    throw new Error(`Failed to load ${folder} index: ${indexUrl} (${res.status})`)
  }
  const data = await res.json()
  const listKey = folder === 'highlights' ? 'highlights' : 'projects'
  const list = Array.isArray(data[listKey]) ? data[listKey] : []
  return list
}

export async function loadProject (slug, folder = 'projects') {
  const base = publicBase()
  const url = `${base}${folder}/${encodeURIComponent(slug)}/project.json`
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`Failed to load ${folder} item "${slug}": ${res.status}`)
  }
  return res.json()
}

/**
 * Loads /<folder>/<slug>/_images.json (sorted filenames of image files in that folder).
 */
export async function loadFolderImageNames (slug, folder = 'projects') {
  const base = publicBase()
  const url = `${base}${folder}/${encodeURIComponent(slug)}/_images.json`
  const res = await fetch(url)
  if (!res.ok) {
    return []
  }
  try {
    const data = await res.json()
    return Array.isArray(data.images) ? data.images : []
  } catch {
    return []
  }
}

/**
 * Uses folder manifest for media.images when project.json does not define `media.images`.
 * If `media.images` is present (including []), it is left unchanged.
 */
export function mergeFolderImagesIntoProject (project, folderImageNames) {
  if (project?.media && Object.prototype.hasOwnProperty.call(project.media, 'images')) {
    return project
  }
  return {
    ...project,
    media: {
      ...(project.media || {}),
      images: folderImageNames
    }
  }
}

export async function loadAllFromFolder (folder = 'projects') {
  const slugs = await loadProjectSlugs(folder)
  const entries = await Promise.all(
    slugs.map(async (slug) => {
      try {
        const project = await loadProject(slug, folder)
        const folderImageNames = await loadFolderImageNames(slug, folder)
        const merged = mergeFolderImagesIntoProject(project, folderImageNames)
        return { slug, project: merged, error: null }
      } catch (e) {
        return { slug, project: null, error: e.message || String(e) }
      }
    })
  )
  return entries
}

export async function loadAllProjects () {
  return loadAllFromFolder('projects')
}

export async function loadAllHighlights () {
  return loadAllFromFolder('highlights')
}
