/**
 * Loads project manifests from /public/projects/ (served as static assets).
 * Image filenames come from each folder's _images.json (generated by scripts/sync-projects-index.js)
 * unless project.json sets media.images explicitly.
 */
function publicBase () {
  return process.env.BASE_URL || '/'
}

export async function loadProjectSlugs () {
  const base = publicBase()
  const indexUrl = `${base}projects/_index.json`
  const res = await fetch(indexUrl)
  if (!res.ok) {
    throw new Error(`Failed to load project index: ${indexUrl} (${res.status})`)
  }
  const data = await res.json()
  const list = Array.isArray(data.projects) ? data.projects : []
  return list
}

export async function loadProject (slug) {
  const base = publicBase()
  const url = `${base}projects/${encodeURIComponent(slug)}/project.json`
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`Failed to load project "${slug}": ${res.status}`)
  }
  return res.json()
}

/**
 * Loads /projects/<slug>/_images.json (sorted filenames of image files in that folder).
 */
export async function loadFolderImageNames (slug) {
  const base = publicBase()
  const url = `${base}projects/${encodeURIComponent(slug)}/_images.json`
  const res = await fetch(url)
  if (!res.ok) {
    return []
  }
  try {
    const data = await res.json()
    return Array.isArray(data.images) ? data.images : []
  } catch {
    return []
  }
}

/**
 * Uses folder manifest for media.images when project.json does not define `media.images`.
 * If `media.images` is present (including []), it is left unchanged.
 */
export function mergeFolderImagesIntoProject (project, folderImageNames) {
  if (project?.media && Object.prototype.hasOwnProperty.call(project.media, 'images')) {
    return project
  }
  return {
    ...project,
    media: {
      ...(project.media || {}),
      images: folderImageNames
    }
  }
}

export async function loadAllProjects () {
  const slugs = await loadProjectSlugs()
  const entries = await Promise.all(
    slugs.map(async (slug) => {
      try {
        const project = await loadProject(slug)
        const folderImageNames = await loadFolderImageNames(slug)
        const merged = mergeFolderImagesIntoProject(project, folderImageNames)
        return { slug, project: merged, error: null }
      } catch (e) {
        return { slug, project: null, error: e.message || String(e) }
      }
    })
  )
  return entries
}
